class_name Episodes
extends RefCounted
## Video senaryoları. Her bölüm bir set ve adımlardan oluşur; adımlar sırayla oynatılır (film_studio.gd).
## "format": "short" (dikey Shorts, 30-60 sn, varsayılan) ya da "long" (yatay uzun bölüm, 5-10 dk).
## Konumlar set noktasıdır ("ev.yatak", bkz. film_sets.gd POINTS) ya da Vector3.
##
## Adımlar:
##   {"title": "yazı", "t": sn}                       ekranın ortasında büyük başlık
##   {"place": "emir", "at": nokta, "look": nokta, "lie": bool}   oyuncuyu sahneye koyar
##   {"cam": nokta, "look": nokta, "t": sn}             kamerayı götürür (t=0 kesme)
##   {"say": "emir", "text": "..."}                     diyalog kutusu; okunma süresi kadar bekler
##   {"walk": "emir", "to": nokta, "wait": false}       yürür (wait false: yürürken sonraki adıma geçer)
##   {"lie": "emir", "value": false}                    yatar/kalkar
##   {"turn": "emir", "to": nokta}                      bir yere döner
##   {"hide": "emir"}                                   sahneden çıkarır
##   {"time": 0.26}                                     günün saati (0.25 gündoğumu, 0.5 öğle)
##   {"wait": sn}
##   {"zoom": sn}                                      komik anda hızlı yakınlaşma
##   {"shake": sn}                                     kamera sarsıntısı
## Yazım kuralları: docs/senaryo-rehberi.md

const LIST := [
	{
		"id": "bolum1", "name": "Bölüm 1: Okul Sabahı", "set": "ev", "time": 0.27,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.ocak", "look": "ev.mutfak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nBölüm 1: Okul Sabahı", "t": 2.5},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 2.0},
			{"say": "emir", "text": "Hıı... Sabah mı oldu?"},
			{"cam": "ev.kam_mutfak", "look": "ev.ocak", "t": 0},
			{"say": "anne", "text": "Emir! Kalk oğlum, okula geç kalacaksın!"},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 0},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"say": "emir", "text": "Tamam anne, geliyorum!"},
			# Odadan mutfağa yürüyüşü gösteren açı (kitaplığın arkasından boş kare çıkmasın).
			{"cam": "ev.kam_mutfak", "look": "ev.mutfak", "t": 0},
			{"walk": "emir", "to": "ev.mutfak"},
			# Anne ocaktan odaya doğru gelir: ikisi de yüzü görünecek şekilde karşılıklı (ocak önü dar, kamera sığmıyordu).
			{"walk": "anne", "to": "ev.mutfak_on"},
			{"turn": "anne", "to": "ev.mutfak"},
			{"turn": "emir", "to": "ev.mutfak_on"},
			{"say": "anne", "text": "Günaydın uykucu! Önce elini yüzünü yıka, sonra kahvaltı."},
			{"say": "emir", "text": "Günaydın anne! Kahvaltıda ne var?"},
			{"say": "anne", "text": "Senin sevdiğin fırın elma ve çilek!"},
			{"say": "emir", "text": "Yaşasın! En sevdiğim!"},
			{"walk": "emir", "to": "ev.canta"},
			{"turn": "emir", "to": Vector3(2.0, 11, 6.5)},  # masadaki çanta/defter
			{"say": "emir", "text": "Çantam, kalemlerim, defterim... Hepsi tamam!"},
			{"walk": "anne", "to": "ev.masa", "wait": false},
			{"walk": "emir", "to": "ev.kapi_ici"},
			{"turn": "emir", "to": "ev.masa"},
			{"say": "anne", "text": "Beslenmeni unutma. Arkadaşlarına iyi davran!"},
			{"say": "emir", "text": "Merak etme anne. Görüşürüz!"},
			{"cam": "ev.kam_kapi", "look": "ev.kapi_disi", "t": 0},
			{"walk": "emir", "to": "ev.yol"},
			{"title": "Yarın: Okulda ilk gün!", "t": 2.5},
		],
	},
	{
		"id": "okul1", "name": "Bölüm 2: Teneffüs", "set": "okul", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "okul.kaydirak", "look": "okul.bahce"},
			{"place": "ali", "at": "okul.bahce", "look": "okul.kaydirak"},
			{"place": "zeynep", "at": "okul.top_alani", "look": "okul.bahce"},
			{"cam": "okul.kam_bahce", "look": "okul.bahce", "t": 0},
			{"title": "EmirCRAFT\nBölüm 2: Teneffüs", "t": 2.5},
			{"say": "ali", "text": "Emir! Saklambaç oynayalım mı?"},
			{"walk": "emir", "to": Vector3(55.5, 11, 17.5)},
			{"turn": "emir", "to": "okul.bahce"},
			{"say": "emir", "text": "Olur! Ama bu sefer ebe sensin Ali!"},
			{"walk": "zeynep", "to": Vector3(53.5, 11, 17.0)},
			{"say": "zeynep", "text": "Ben de varım! Kum havuzunun arkasına saklanacağım."},
			{"say": "ali", "text": "Tamam, gözlerimi kapatıyorum. Bir... iki... üç..."},
			{"walk": "emir", "to": "okul.sinif_kapi", "wait": false},
			{"walk": "zeynep", "to": "okul.top_alani"},
			{"say": "ali", "text": "...on! Önüm arkam sağım solum sobe!"},
			{"cam": "okul.kam_sinif", "look": "okul.sinif_kapi", "t": 1.5},
			{"say": "emir", "text": "Hiii... Sınıfa saklandım, burayı asla bulamaz!"},
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"say": "ogretmen", "text": "Emir? Teneffüste sınıfta ne arıyorsun?"},
			{"turn": "emir", "to": "okul.tahta"},
			{"say": "emir", "text": "Şşş öğretmenim! Saklambaç oynuyoruz!"},
			{"say": "ogretmen", "text": "Hahaha! O zaman ben seni görmedim."},
			{"title": "Ali Emir'i bulabilecek mi?\nDevamı gelecek bölümde!", "t": 3.0},
		],
	},
	{
		"id": "hasta", "name": "Bölüm 3: Sahte Hasta", "set": "ev", "time": 0.28,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.kapi_ici", "look": "ev.yatak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nBölüm 3: Sahte Hasta", "t": 2.5},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 1.5},
			{"say": "emir", "text": "(Bugün matematik sınavı var... Bir planım var!)"},
			{"say": "emir", "text": "Anneee... Öhö öhö! Çok hastayım, okula gidemem..."},
			{"walk": "anne", "to": "ev.yatak_yani"},
			{"turn": "anne", "to": "ev.yatak"},
			{"say": "anne", "text": "Hmm... Ateşin var mı bakalım?"},
			{"say": "emir", "text": "Evet! Çok yüksek! Belki bin derece!"},
			{"say": "anne", "text": "Bin derece mi? O zaman bugünkü lunaparka gidemeyiz..."},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"turn": "anne", "to": "ev.yatak_yani"},
			{"say": "emir", "text": "LUNAPARK MI?! İyileştim! Mucize oldu!"},
			{"say": "anne", "text": "Hahaha! Lunapark hafta sonu. Şimdi hadi okula, sınavın var!"},
			{"say": "emir", "text": "Eyvah... Yakalandım!"},
			{"title": "Yalan söyleyen yakalanır!", "t": 2.5},
		],
	},
	{
		"id": "odev", "name": "Bölüm 4: Ödevi Köpek Yedi", "set": "okul", "time": 0.35,
		"steps": [
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"place": "ali", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "zeynep", "at": "okul.sira_2", "look": "okul.tahta"},
			{"place": "emir", "at": "okul.sira_3", "look": "okul.tahta"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"title": "EmirCRAFT\nBölüm 4: Ödevi Köpek Yedi", "t": 2.5},
			{"say": "ogretmen", "text": "Günaydın çocuklar! Ödevlerinizi toplayalım."},
			{"say": "zeynep", "text": "Buyurun öğretmenim, iki sayfa yazdım!"},
			{"say": "ogretmen", "text": "Aferin Zeynep! Ali, senin ödevin?"},
			{"say": "ali", "text": "Öğretmenim... Ödevimi köpeğim yedi!"},
			{"say": "ogretmen", "text": "Ali, senin köpeğin yok ki."},
			{"say": "ali", "text": "Eee... Komşunun köpeği! Çok acıkmıştı!"},
			{"cam": "okul.kam_tahta", "look": "okul.sira_3", "t": 1.0},
			{"say": "ogretmen", "text": "Peki Emir, senin ödevin nerede?"},
			{"say": "emir", "text": "Benimki burada öğretmenim! Ama biraz... ıslak."},
			{"say": "ogretmen", "text": "Islak mı? Ne oldu ona?"},
			{"say": "emir", "text": "Ali'nin komşusunun köpeği onu da yalamış!"},
			{"say": "zeynep", "text": "Hahaha! O köpek bütün sınıfın ödevini yiyecek!"},
			{"say": "ogretmen", "text": "Tamam, tamam! Yarın ödevler kuru ve eksiksiz gelsin!"},
			{"title": "Ödevini zamanında yap,\nköpeğe fırsat verme!", "t": 3.0},
		],
	},
	{
		"id": "noobpro", "name": "Bölüm 5: Acemi vs Usta", "set": "ev", "time": 0.3,
		"steps": [
			{"place": "ali", "at": "ev.masa", "look": "ev.ocak"},
			{"place": "zeynep", "at": "ev.mutfak", "look": "ev.ocak"},
			{"cam": "ev.kam_mutfak", "look": "ev.masa", "t": 0},
			{"title": "Acemi vs Usta: Kahvaltı", "t": 1.3},
			{"say": "ali", "text": "Acemi kahvaltı hazırlıyor..."},
			{"say": "ali", "text": "Elmayı ocağa koydum, on saat bekleyeceğim!"},
			{"zoom": 0.4},
			{"cam": "ev.kam_oda", "look": "ev.mutfak", "t": 0},
			{"say": "zeynep", "text": "Usta kahvaltı hazırlıyor!"},
			{"say": "zeynep", "text": "Fırın elma, çilek, hepsi on saniyede hazır!"},
			{"place": "emir", "at": "ev.kapi_ici", "look": "ev.mutfak"},
			{"cam": "ev.kam_yatak", "look": "ev.kapi_ici", "t": 0},
			{"say": "emir", "text": "Peki ya dâhi kahvaltı?"},
			{"walk": "emir", "to": "ev.masa"},
			{"say": "emir", "text": "Anneeee! Kahvaltı hazır mı?"},
			{"place": "anne", "at": "ev.ocak", "look": "ev.masa"},
			{"shake": 0.4},
			{"say": "anne", "text": "Hazır oğlum, gel otur!"},
			{"zoom": 0.5},
			{"say": "emir", "text": "İşte dâhi yöntemi: Annem!"},
			{"title": "Sen hangisisin?\nYorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "uzun1", "name": "Uzun 1: Büyük Okul Günü", "set": "ev", "time": 0.27, "format": "long",
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.ocak", "look": "ev.mutfak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nEmir'in Büyük Okul Günü", "t": 3.0},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 2.5},
			{"say": "emir", "text": "Hıı... Rüyamda dev bir çilek beni kovalıyordu..."},
			{"say": "emir", "text": "Neyse ki uyandım. Bugün günlerden ne?"},
			{"say": "emir", "text": "Dur bir dakika... Bugün okulda BİLİM FUARI var!"},
			{"zoom": 0.5},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"say": "emir", "text": "Anneee! Bilim fuarı bugün! Projemi unuttum!"},
			{"cam": "ev.kam_mutfak", "look": "ev.ocak", "t": 0},
			{"say": "anne", "text": "Sakin ol Emir. Önce derin bir nefes al."},
			{"say": "anne", "text": "Proje ne hakkında olacaktı?"},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 1.2},
			{"walk": "emir", "to": "ev.mutfak"},
			{"turn": "emir", "to": "ev.ocak"},
			{"turn": "anne", "to": "ev.mutfak"},
			{"say": "emir", "text": "Bitkiler güneşten nasıl yemek yapar, onu anlatacaktım."},
			{"say": "emir", "text": "Ama saksım da yok, bitkim de yok!"},
			{"say": "anne", "text": "Bahçede çilek çalıları var ya?"},
			{"say": "emir", "text": "Evet ama çalıyı okula nasıl götüreceğim?"},
			{"say": "anne", "text": "Küçük bir dalını saksıya dikeriz. Hadi, beraber yapalım!"},
			{"say": "emir", "text": "Sen dünyanın en iyi annesisin!"},
			{"say": "anne", "text": "Biliyorum. Ama önce kahvaltı!"},
			{"walk": "anne", "to": "ev.masa", "wait": false},
			{"walk": "emir", "to": "ev.masa"},
			{"cam": "ev.kam_yatak", "look": "ev.masa", "t": 0},
			{"say": "emir", "text": "Fırın elma! Mmm, kokusu harika."},
			{"say": "anne", "text": "Yemek yerken acele etme, boğazına kaçar."},
			{"say": "emir", "text": "Acele etmiyorum... Sadece çok hızlı çiğniyorum!"},
			{"say": "anne", "text": "Hahaha. Peki fuarda kime göstereceksin projeni?"},
			{"say": "emir", "text": "Öğretmenime, Ali'ye, Zeynep'e... Bütün okula!"},
			{"say": "emir", "text": "Ali roket yapıyormuş. Zeynep de yanardağ!"},
			{"say": "anne", "text": "Yanardağ mı? Umarım sınıfı köpüğe boğmaz."},
			{"say": "emir", "text": "Boğarsa çok eğlenceli olur!"},
			{"zoom": 0.4},
			{"cam": "ev.kam_kapi", "look": "ev.bahce", "t": 0},
			{"place": "emir", "at": "ev.kapi_disi", "look": "ev.bahce"},
			{"place": "anne", "at": "ev.kapi_ici", "look": "ev.bahce"},
			{"walk": "emir", "to": "ev.bahce"},
			{"walk": "anne", "to": Vector3(7.0, 11, 10.0)},
			{"say": "anne", "text": "İşte burada. En sağlam dalı seçelim."},
			{"say": "emir", "text": "Bu mu? Bunun üstünde üç tane çilek var!"},
			{"say": "anne", "text": "Çilekleri yeme ama! Projen bunlar."},
			{"say": "emir", "text": "Bir tanecik bile mi?"},
			{"say": "anne", "text": "Bir tanecik. Diğerleri jüri için."},
			{"say": "emir", "text": "Anlaştık!"},
			{"say": "emir", "text": "Mmm... Bilimin tadı çok güzelmiş!"},
			{"shake": 0.3},
			{"cam": "ev.kam_kapi", "look": "ev.kapi_disi", "t": 0},
			{"walk": "emir", "to": "ev.kapi_disi"},
			{"turn": "emir", "to": "ev.bahce"},
			{"say": "anne", "text": "Saksın hazır. Dikkatli taşı, düşürme!"},
			{"say": "emir", "text": "Merak etme! Görüşürüz anne!"},
			{"say": "anne", "text": "İyi şanslar küçük bilim insanı!"},
			{"walk": "emir", "to": "ev.yol"},
			{"hide": "anne"},
			{"hide": "emir"},
			{"title": "Okulda...", "t": 2.0},
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"place": "ali", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "zeynep", "at": "okul.sira_2", "look": "okul.tahta"},
			{"place": "emir", "at": "okul.sinif_kapi", "look": "okul.tahta"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"say": "ogretmen", "text": "Günaydın çocuklar! Bugün büyük gün!"},
			{"say": "ogretmen", "text": "Bilim fuarına hoş geldiniz!"},
			{"say": "emir", "text": "Yetiştim! Günaydın öğretmenim!"},
			{"walk": "emir", "to": "okul.sira_3"},
			{"turn": "emir", "to": "okul.tahta"},
			{"say": "ogretmen", "text": "İlk proje Ali'den. Buyur Ali!"},
			{"walk": "ali", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "ali", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "ali", "text": "Bu benim roketim! Kartondan ve bantlardan yaptım."},
			{"say": "ali", "text": "Üç deyince fırlayacak! Bir... iki... ÜÇ!"},
			{"shake": 0.6},
			{"say": "ali", "text": "..."},
			{"say": "ali", "text": "Eee... Galiba yakıtı unuttum."},
			{"say": "zeynep", "text": "Hahaha! Roketin uyuyor Ali!"},
			{"say": "ogretmen", "text": "Çok güzel bir tasarım Ali. Yakıtı da gelecek sefere!"},
			{"walk": "ali", "to": "okul.sira_1"},
			{"cam": "okul.kam_sinif", "look": "okul.sira_2", "t": 0},
			{"say": "ogretmen", "text": "Sırada Zeynep var. Yanardağ projesi!"},
			{"walk": "zeynep", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "zeynep", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "zeynep", "text": "Yanardağımın içine karbonat koydum."},
			{"say": "zeynep", "text": "Şimdi de sirke ekliyorum. Geri çekilin!"},
			{"shake": 0.8},
			{"zoom": 0.6},
			{"say": "ali", "text": "Vaaay! Köpükler her yere taşıyor!"},
			{"say": "emir", "text": "Sınıf köpük banyosu oldu!"},
			{"say": "ogretmen", "text": "Zeynep! Bu kadar köpük olacağını söylememiştin!"},
			{"say": "zeynep", "text": "Ben de bilmiyordum öğretmenim! Bilim bu!"},
			{"say": "ogretmen", "text": "Hahaha! Tamam tamam, harika bir deney oldu."},
			{"walk": "zeynep", "to": "okul.sira_2"},
			{"cam": "okul.kam_sinif", "look": "okul.sira_3", "t": 0},
			{"say": "ogretmen", "text": "Son proje Emir'den. Hadi Emir!"},
			{"walk": "emir", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "emir", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "emir", "text": "Bu benim çilek bitkim. Sabah annemle diktik."},
			{"say": "emir", "text": "Bitkiler güneşten ışık alır, havadan da nefes alır."},
			{"say": "emir", "text": "Topraktan suyu çekerler ve kendi yemeklerini yaparlar!"},
			{"say": "emir", "text": "Buna fotosentez denir. Fo-to-sen-tez!"},
			{"say": "ogretmen", "text": "Harika anlattın Emir! Peki çilekler nerede?"},
			{"say": "emir", "text": "Şey... Üç tane vardı öğretmenim..."},
			{"say": "emir", "text": "Biri bilim için test edildi."},
			{"say": "ali", "text": "Test mi? Yedin yani!"},
			{"say": "emir", "text": "Bilimsel olarak tadına baktım!"},
			{"zoom": 0.5},
			{"say": "zeynep", "text": "Hahaha! En lezzetli proje seninki!"},
			{"say": "ogretmen", "text": "Hepiniz çok güzel çalıştınız çocuklar."},
			{"say": "ogretmen", "text": "Bugünün ödülü... hepinize birer çilek!"},
			{"say": "emir", "text": "Yaşasın! Bu sefer yemek serbest!"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 2.0},
			{"title": "Bilim eğlencelidir!\nBir sonraki bölümde görüşürüz!", "t": 3.5},
		],
	},
	{
		"id": "cilek", "name": "Bölüm 6: Çilek Karnı", "set": "hastane", "time": 0.45,
		"steps": [
			{"place": "emir", "at": "hastane.yatak_1", "lie": true},
			{"place": "anne", "at": "hastane.yatak_1_yani", "look": "hastane.yatak_1"},
			{"place": "doktor", "at": "hastane.danisma_arka", "look": "hastane.yatak_1"},
			{"cam": "hastane.kam_dis", "look": "hastane.giris", "t": 0},
			{"title": "Çilek Karnı", "t": 1.3},
			{"cam": "hastane.kam_yatak", "look": "hastane.yatak_1", "t": 0},
			{"say": "emir", "text": "Aaah karnım! Çok ağrıyor!"},
			{"say": "anne", "text": "Doktor bey, lütfen bakar mısınız?"},
			{"walk": "doktor", "to": Vector3(-38.6, 11, 3.6)},
			{"turn": "doktor", "to": "hastane.yatak_1"},
			{"say": "doktor", "text": "Merhaba Emir. Bugün ne yedin bakalım?"},
			{"say": "emir", "text": "Hiç! Sadece birkaç çilek..."},
			{"say": "anne", "text": "Birkaç mı? Bütün çalıyı bitirmişsin!"},
			{"zoom": 0.5},
			{"say": "doktor", "text": "Kaç tane yedin Emir?"},
			{"say": "emir", "text": "Sayamadım ki... Çok hızlı yedim!"},
			{"say": "doktor", "text": "Teşhis belli: Çilek karnı!"},
			{"say": "doktor", "text": "İlacın: bol su ve bugün hiç çilek yok."},
			{"shake": 0.4},
			{"say": "emir", "text": "HİÇ Mİ?! Bu ilaç çok acı doktor bey!"},
			{"say": "anne", "text": "Hahaha! Her şeyin fazlası zarar oğlum."},
			{"title": "Her şeyin azı karar,\nçoğu zarar!", "t": 2.5},
		],
	},
	{
		"id": "bakkal1", "name": "Bölüm 7: Çilekle Alışveriş", "set": "bakkal", "time": 0.4,
		"steps": [
			{"place": "bakkal", "at": "bakkal.tezgah_arka", "look": "bakkal.kapi"},
			{"place": "emir", "at": "bakkal.dis", "look": "bakkal.kapi"},
			{"cam": "bakkal.kam_dis", "look": "bakkal.kapi", "t": 0},
			{"title": "Çilekle Alışveriş", "t": 1.3},
			{"say": "emir", "text": "Bugün dondurma alacağım! Param da hazır!"},
			{"cam": "bakkal.kam_ic", "look": "bakkal.tezgah_on", "t": 0},
			{"walk": "emir", "to": "bakkal.tezgah_on"},
			{"turn": "emir", "to": "bakkal.tezgah_arka"},
			{"say": "bakkal", "text": "Hoş geldin Emir! Ne alıyorsun?"},
			{"say": "emir", "text": "En büyük çikolatalı dondurma lütfen!"},
			{"say": "bakkal", "text": "Buyur. Beş lira oluyor."},
			{"cam": "bakkal.kam_tezgah", "look": "bakkal.tezgah_on", "t": 0},
			{"say": "emir", "text": "Buyurun! Beş tane çilek!"},
			{"zoom": 0.6},
			{"say": "bakkal", "text": "Çilek mi? Evladım bu para değil ki!"},
			{"say": "emir", "text": "Ama oyunda çilekle her şey alınıyor!"},
			{"say": "bakkal", "text": "Hahaha! Burası gerçek bakkal, oyun değil!"},
			{"shake": 0.3},
			{"say": "emir", "text": "Peki... Çilekli dondurma yapar mısınız?"},
			{"say": "bakkal", "text": "Anlaştık! Çilekleri ver, dondurma benden!"},
			{"say": "emir", "text": "Yaşasın! Takas en iyi alışveriş!"},
			{"title": "Sen olsan ne ile takas ederdin?\nYorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "beklenti", "name": "Bölüm 8: Beklenti vs Gerçek", "set": "ev", "time": 0.32,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 0},
			{"title": "Hafta sonu\nBEKLENTİ", "t": 1.3},
			{"say": "emir", "text": "Cumartesi! Öğlene kadar uyuyacağım!"},
			{"say": "emir", "text": "Sonra bütün gün oyun oynayacağım!"},
			{"title": "GERÇEK", "t": 1.2},
			{"place": "anne", "at": "ev.yatak_yani", "look": "ev.yatak"},
			{"shake": 0.4},
			{"say": "anne", "text": "EMİİİR! Saat sekiz, kalk!"},
			{"zoom": 0.5},
			{"say": "emir", "text": "Ama anne, bugün cumartesi!"},
			{"say": "anne", "text": "Biliyorum. Bugün büyük temizlik günü!"},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"place": "anne", "at": "ev.masa", "look": "ev.yatak_yani"},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 0},
			{"say": "anne", "text": "Önce odanı topla, sonra bulaşıklar."},
			{"say": "emir", "text": "Ya oyun ne zaman?"},
			{"say": "anne", "text": "Temizlik bitince! Hem temizlik de bir oyun."},
			{"walk": "emir", "to": "ev.canta"},
			{"say": "emir", "text": "Adı: Oda Toplama Yarışı! Başla!"},
			{"walk": "emir", "to": "ev.mutfak"},
			{"walk": "emir", "to": "ev.yatak_yani"},
			{"say": "emir", "text": "Bitti! Dünya rekoru!"},
			{"say": "anne", "text": "Aferin! Oyun zamanı!"},
			{"say": "emir", "text": "Yaşasın! Ama önce... biraz uyuyayım."},
			{"title": "Senin hafta sonun nasıl geçiyor?", "t": 2.5},
		],
	},
	{
		"id": "sobe", "name": "Bölüm 9: Sobe!", "set": "okul", "time": 0.42,
		"steps": [
			{"place": "emir", "at": Vector3(55.0, 11, 1.8), "look": "okul.sinif_kapi"},
			{"place": "ogretmen", "at": Vector3(54.5, 11, 2.8), "look": "okul.sinif_kapi"},
			{"place": "ali", "at": "okul.bahce", "look": "okul.sinif_kapi"},
			{"place": "zeynep", "at": "okul.top_alani", "look": "okul.bahce"},
			{"cam": "okul.kam_bahce", "look": "okul.bahce", "t": 0},
			{"title": "Sobe! (Teneffüs 2)", "t": 1.3},
			{"say": "ali", "text": "Zeynep'i buldum! Sıra Emir'de..."},
			{"walk": "ali", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"say": "emir", "text": "(Öğretmenin arkasındayım, beni asla bulamaz!)"},
			{"walk": "ali", "to": "okul.sira_3"},
			{"say": "ali", "text": "Emir? Buralarda mısın?"},
			{"say": "ogretmen", "text": "Ali, burada kimse yok. Sadece ben varım."},
			{"say": "ali", "text": "Peki öğretmenim, arkanızdaki kırmızı tişört kimin?"},
			{"zoom": 0.6},
			{"say": "emir", "text": "Eyvah! Tişörtüm beni ele verdi!"},
			{"say": "ali", "text": "Önüm arkam sağım solum SOBE!"},
			{"shake": 0.4},
			{"say": "ogretmen", "text": "Hahaha! Bir dahaki sefere yeşil giy Emir!"},
			{"say": "emir", "text": "Not aldım: Kamuflaj önemli!"},
			{"title": "Sen en iyi nereye saklanırdın?\nYorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "piknik", "name": "Bölüm 10: Piknik Hırsızı", "set": "park", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "park.ortu_yani", "look": "park.ortu"},
			{"place": "anne", "at": "park.bank", "look": "park.ortu"},
			{"place": "ali", "at": "park.agac", "look": "park.ortu"},
			{"cam": "park.kam_genel", "look": "park.ortu", "t": 0},
			{"title": "Piknik Hırsızı", "t": 1.3},
			{"cam": "park.kam_ortu", "look": "park.ortu", "t": 0},
			{"say": "emir", "text": "Piknik sepetinde on tane kurabiye vardı!"},
			{"say": "emir", "text": "Şimdi sadece üç tane kaldı. Bir hırsız var!"},
			{"zoom": 0.5},
			{"say": "emir", "text": "Dedektif Emir göreve başlıyor!"},
			{"walk": "emir", "to": "park.bank_yani"},
			{"turn": "emir", "to": "park.bank"},
			{"cam": "park.kam_bank", "look": "park.bank", "t": 0},
			{"say": "emir", "text": "Anne, kurabiyeleri sen mi yedin?"},
			{"say": "anne", "text": "Ben mi? Ben sadece çay içtim!"},
			{"walk": "emir", "to": Vector3(44.5, 11, -24.0)},
			{"turn": "emir", "to": "park.agac"},
			{"cam": "park.kam_genel", "look": "park.agac", "t": 0},
			{"say": "emir", "text": "Ali! Ağacın arkasında ne yapıyorsun?"},
			{"say": "ali", "text": "Hiç! Kuş seyrediyorum..."},
			{"say": "emir", "text": "Peki ağzındaki kurabiye kırıntıları ne?"},
			{"shake": 0.4},
			{"say": "ali", "text": "Eee... Kuşlar kurabiye yiyormuş, ben de denedim!"},
			{"say": "emir", "text": "Dava çözüldü! Ceza: Kurabiyeleri paylaşacağız!"},
			{"say": "ali", "text": "En güzel ceza bu!"},
			{"title": "Paylaşınca daha lezzetli!", "t": 2.5},
		],
	},
	{
		"id": "asi", "name": "Bölüm 11: Aşı Günü", "set": "hastane", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "hastane.bekleme", "look": "hastane.danisma"},
			{"place": "anne", "at": Vector3(-38.0, 11, 7.6), "look": "hastane.bekleme"},
			{"place": "doktor", "at": "hastane.danisma_arka", "look": "hastane.danisma"},
			{"cam": "hastane.kam_ic", "look": "hastane.bekleme", "t": 0},
			{"title": "Aşı Günü", "t": 1.3},
			{"say": "emir", "text": "Anne, ben aslında hiç hasta değilim. Gidelim mi?"},
			{"say": "anne", "text": "Aşı hasta olmamak için yapılır Emir."},
			{"say": "doktor", "text": "Sıradaki kahramanımız... Emir!"},
			{"zoom": 0.5},
			{"say": "emir", "text": "Kahraman mı? Ben mi?"},
			{"walk": "emir", "to": "hastane.danisma"},
			{"turn": "emir", "to": "hastane.danisma_arka"},
			{"say": "doktor", "text": "Evet! Aşı olan herkes mikroplara karşı süper güç kazanır."},
			{"say": "emir", "text": "Süper güç mü? Tamam, hazırım! Gözlerimi kapatıyorum..."},
			{"say": "doktor", "text": "Bitti bile!"},
			{"shake": 0.3},
			{"say": "emir", "text": "Ne? Hiç acımadı! Karınca ısırığı gibiydi!"},
			{"say": "anne", "text": "Gördün mü? Korkulacak bir şey yokmuş."},
			{"say": "emir", "text": "Artık mikroplar benden korksun!"},
			{"title": "Aşı olan süper kahraman olur!", "t": 2.5},
		],
	},
	{
		"id": "uzun2", "name": "Uzun 2: Kayıp Hazine Haritası", "set": "park", "time": 0.4, "format": "long",
		"steps": [
			{"place": "emir", "at": "park.ortu_yani", "look": "park.ortu"},
			{"place": "ali", "at": "park.bank_yani", "look": "park.ortu"},
			{"place": "zeynep", "at": "park.agac", "look": "park.ortu"},
			{"cam": "park.kam_genel", "look": "park.ortu", "t": 0},
			{"title": "EmirCRAFT\nKayıp Hazine Haritası", "t": 3.0},
			{"cam": "park.kam_ortu", "look": "park.ortu", "t": 1.5},
			{"say": "emir", "text": "Arkadaşlar! Sandığın dibinde eski bir kâğıt buldum!"},
			{"say": "emir", "text": "Bakın... Bu bir hazine haritası!"},
			{"zoom": 0.5},
			{"walk": "ali", "to": Vector3(49.0, 11, -27.0)},
			{"walk": "zeynep", "to": Vector3(51.5, 11, -28.5)},
			{"say": "ali", "text": "Hazine mi? Altın mı? Elmas mı?"},
			{"say": "zeynep", "text": "Dur Ali, önce haritayı okuyalım."},
			{"say": "zeynep", "text": "Burada üç ipucu yazıyor."},
			{"say": "emir", "text": "Birinci ipucu: Beyaz duvarlı, kırmızı artılı yer."},
			{"say": "ali", "text": "Kolay! Hastane!"},
			{"say": "zeynep", "text": "İkinci ipucu: Çizgili tenteli, her şeyin satıldığı yer."},
			{"say": "emir", "text": "Bakkal Amca'nın dükkânı!"},
			{"say": "zeynep", "text": "Üçüncü ipucu: Her sabah uyandığın yer."},
			{"say": "ali", "text": "Bu kimin evi olabilir?"},
			{"say": "emir", "text": "Hmm... Bunu sonra düşünelim. Önce hastane!"},
			{"shake": 0.3},
			{"hide": "ali"},
			{"hide": "zeynep"},
			{"hide": "emir"},
			{"title": "Birinci durak: Hastane", "t": 2.0},
			{"place": "doktor", "at": "hastane.danisma_arka", "look": "hastane.danisma"},
			{"place": "emir", "at": "hastane.giris", "look": "hastane.danisma"},
			{"place": "ali", "at": Vector3(-34.5, 11, 9.0), "look": "hastane.danisma"},
			{"place": "zeynep", "at": Vector3(-32.5, 11, 9.0), "look": "hastane.danisma"},
			{"cam": "hastane.kam_ic", "look": "hastane.danisma", "t": 0},
			{"walk": "emir", "to": "hastane.danisma"},
			{"say": "doktor", "text": "Merhaba çocuklar! Kimse hasta değil umarım?"},
			{"say": "emir", "text": "Hayır doktor bey. Bir hazine haritası takip ediyoruz!"},
			{"say": "doktor", "text": "Hazine mi? O zaman size bir ipucum var."},
			{"say": "doktor", "text": "Ama önce bir soru: Mikroplardan korunmak için ne yaparız?"},
			{"say": "ali", "text": "Ellerimizi yıkarız!"},
			{"say": "zeynep", "text": "Ve aşılarımızı oluruz!"},
			{"say": "doktor", "text": "Bravo! İşte ipucunuz: Bakkalda dondurma dolabına bakın."},
			{"say": "emir", "text": "Teşekkürler doktor bey! Hadi arkadaşlar!"},
			{"hide": "emir"},
			{"hide": "ali"},
			{"hide": "zeynep"},
			{"hide": "doktor"},
			{"title": "İkinci durak: Bakkal", "t": 2.0},
			{"place": "bakkal", "at": "bakkal.tezgah_arka", "look": "bakkal.kapi"},
			{"place": "emir", "at": "bakkal.kapi", "look": "bakkal.tezgah_arka"},
			{"place": "ali", "at": Vector3(4.0, 11, -27.8), "look": "bakkal.tezgah_arka"},
			{"place": "zeynep", "at": Vector3(7.0, 11, -27.8), "look": "bakkal.tezgah_arka"},
			{"cam": "bakkal.kam_tezgah", "look": "bakkal.tezgah_on", "t": 0},
			{"walk": "emir", "to": "bakkal.tezgah_on"},
			{"say": "bakkal", "text": "Hoş geldiniz çocuklar! Bugün çok kalabalıksınız."},
			{"say": "emir", "text": "Bakkal Amca, dondurma dolabına bakabilir miyiz?"},
			{"say": "bakkal", "text": "Tabii! Ama bir dondurma alırsanız."},
			{"walk": "ali", "to": "bakkal.dondurma"},
			{"turn": "ali", "to": "bakkal.tezgah_arka"},
			{"say": "ali", "text": "Buldum! Dolabın arkasında bir not var!"},
			{"say": "zeynep", "text": "Oku, oku!"},
			{"say": "ali", "text": "Hazine, her sabah uyandığın yerde, yastığın altında!"},
			{"say": "emir", "text": "Yastık mı? Benim yastığım mı?!"},
			{"say": "bakkal", "text": "Hahaha! Anlaşılan hazine senin evinde Emir."},
			{"say": "emir", "text": "Hadi eve koşalım!"},
			{"shake": 0.3},
			{"hide": "emir"},
			{"hide": "ali"},
			{"hide": "zeynep"},
			{"hide": "bakkal"},
			{"title": "Son durak: Emir'in evi", "t": 2.0},
			{"place": "anne", "at": "ev.masa", "look": "ev.kapi_ici"},
			{"place": "emir", "at": "ev.kapi_ici", "look": "ev.yatak"},
			{"place": "ali", "at": Vector3(3.5, 11, 5.8), "look": "ev.yatak"},
			{"place": "zeynep", "at": Vector3(5.5, 11, 5.8), "look": "ev.yatak"},
			{"cam": "ev.kam_oda", "look": "ev.kapi_ici", "t": 0},
			{"say": "anne", "text": "Aa, hoş geldiniz! Neden bu kadar heyecanlısınız?"},
			{"say": "emir", "text": "Anne, yastığımın altında hazine varmış!"},
			{"walk": "emir", "to": "ev.yatak_yani"},
			{"turn": "emir", "to": "ev.yatak"},
			{"cam": "ev.kam_yatak", "look": "ev.yatak_yani", "t": 1.0},
			{"say": "emir", "text": "Bir... İki... Üç... Kaldırıyorum!"},
			{"zoom": 0.8},
			{"say": "emir", "text": "Bir mektup var! Ve dört tane çikolata!"},
			{"say": "zeynep", "text": "Mektupta ne yazıyor?"},
			{"say": "emir", "text": "Sevgili hazine avcıları, hazine aslında arkadaşlıktır."},
			{"say": "emir", "text": "Çikolatalar da paylaşmanız için. İmza: Anne!"},
			{"turn": "emir", "to": "ev.masa"},
			{"say": "anne", "text": "Sürpriz! Haritayı ben hazırladım."},
			{"say": "ali", "text": "Doktor bey ve Bakkal Amca da biliyor muydu?"},
			{"say": "anne", "text": "Tabii! Onlar da bu oyunun parçasıydı."},
			{"say": "zeynep", "text": "Bu şimdiye kadarki en güzel macera!"},
			{"say": "ali", "text": "Ama bir sorun var... Dört çikolata, üç kişiyiz."},
			{"say": "emir", "text": "O zaman dördüncüsü, en iyi hazine avcısı için!"},
			{"say": "anne", "text": "Yani bana mı? Teşekkürler!"},
			{"shake": 0.3},
			{"say": "emir", "text": "Hahaha! Anneme de hazine kaldı!"},
			{"cam": "ev.kam_mutfak", "look": "ev.yatak_yani", "t": 2.0},
			{"title": "Gerçek hazine arkadaşlıktır!\nBir sonraki maceraya kadar hoşça kalın!", "t": 3.5},
		],
	},
	{
		"id": "dis", "name": "Bölüm 12: Diş Fırçası Kaçağı", "set": "ev", "time": 0.8,
		"steps": [
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.yatak"},
			{"place": "anne", "at": "ev.mutfak", "look": "ev.yatak_yani"},
			{"cam": "ev.kam_yatak", "look": "ev.yatak_yani", "t": 0},
			{"title": "Diş Fırçası Kaçağı", "t": 1.3},
			{"say": "emir", "text": "Gizli görev: Dişlerimi fırçalamadan yatağa gir!"},
			{"lie": "emir", "value": true},
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"say": "emir", "text": "Başardım! Kimse fark etmedi..."},
			{"cam": "ev.kam_mutfak", "look": "ev.mutfak", "t": 0},
			{"say": "anne", "text": "Emir? Diş fırçan neden kupkuru?"},
			{"zoom": 0.6},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 0},
			{"say": "emir", "text": "Eee... Çok hızlı fırçaladım, hemen kurudu!"},
			{"walk": "anne", "to": "ev.yatak_yani"},
			{"turn": "anne", "to": "ev.yatak"},
			{"say": "anne", "text": "Öyle mi? O zaman bir gülümse bakalım."},
			{"say": "emir", "text": "Iıı... Tamam, yakalandım!"},
			{"shake": 0.3},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.canta", "look": "ev.yatak_yani"},
			{"say": "anne", "text": "Mikroplar gece partisi yapmasın!"},
			{"say": "emir", "text": "Tamam! Mikroplar, parti iptal!"},
			{"title": "Yatmadan önce dişlerini fırçaladın mı?", "t": 2.5},
		],
	},
	{
		"id": "sinav", "name": "Bölüm 13: Sürpriz Sınav", "set": "okul", "time": 0.35,
		"steps": [
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sira_1"},
			{"place": "emir", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "ali", "at": "okul.sira_2", "look": "okul.tahta"},
			{"place": "zeynep", "at": "okul.sira_3", "look": "okul.tahta"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"title": "Sürpriz Sınav", "t": 1.3},
			{"say": "ogretmen", "text": "Çocuklar, kâğıtları çıkarın. Sürpriz sınav!"},
			{"zoom": 0.6},
			{"shake": 0.4},
			{"say": "ali", "text": "Ne?! Bugün sınav yoktu ki!"},
			{"cam": "okul.kam_tahta", "look": "okul.sira_1", "t": 0},
			{"say": "emir", "text": "Sakin ol Ali. Benim bir planım var."},
			{"say": "emir", "text": "Öğretmenim! Bugün sizin doğum gününüz değil mi?"},
			{"turn": "ogretmen", "to": "okul.sira_1"},
			{"say": "ogretmen", "text": "Hayır Emir. Doğum günüm yazın."},
			{"say": "zeynep", "text": "Plan A başarısız oldu..."},
			{"say": "emir", "text": "Plan B: Öğretmenim, kaleminiz çok güzelmiş!"},
			{"say": "ogretmen", "text": "Teşekkürler. Sınav yine de var."},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"say": "ali", "text": "Tamam, pes ediyoruz. İlk soru ne?"},
			{"say": "ogretmen", "text": "Soru bir: Adın ne?"},
			{"zoom": 0.6},
			{"say": "emir", "text": "Bunu biliyorum! Yüz aldım!"},
			{"say": "ogretmen", "text": "Şaka yaptım, sınav yok. Bugün 1 Nisan!"},
			{"shake": 0.3},
			{"say": "ali", "text": "Öğretmenim bizi trolledi!"},
			{"title": "Sen olsan hangi planı denerdin? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "dondurma", "name": "Bölüm 14: Son Dondurma", "set": "bakkal", "time": 0.45,
		"steps": [
			{"place": "bakkal", "at": "bakkal.tezgah_arka", "look": "bakkal.tezgah_on"},
			{"place": "emir", "at": "bakkal.kapi", "look": "bakkal.dondurma"},
			{"place": "ali", "at": "bakkal.dis", "look": "bakkal.kapi"},
			{"cam": "bakkal.kam_dis", "look": "bakkal.kapi", "t": 0},
			{"title": "Son Dondurma", "t": 1.3},
			{"say": "emir", "text": "Dolapta tek bir dondurma kaldı. O benim!"},
			{"walk": "emir", "to": "bakkal.dondurma", "wait": false},
			{"walk": "ali", "to": "bakkal.tezgah_on"},
			{"cam": "bakkal.kam_ic", "look": "bakkal.tezgah_on", "t": 0},
			{"say": "ali", "text": "Amca, son dondurmayı ben alıyorum!"},
			{"zoom": 0.6},
			{"say": "emir", "text": "Hayır! Ona ben önce baktım!"},
			{"say": "bakkal", "text": "Kavga yok çocuklar. Kim güzel bir fıkra anlatırsa onun."},
			{"say": "ali", "text": "Temel bakkala gitmiş... Eee, gerisini unuttum."},
			{"say": "emir", "text": "Benimki kısa: Dondurma neden üşür? Çünkü hep dolapta!"},
			{"say": "bakkal", "text": "Hahaha! Tamam, kazanan Emir."},
			{"shake": 0.3},
			{"turn": "emir", "to": "bakkal.tezgah_on"},
			{"say": "emir", "text": "Ali, al ikiye bölelim. Kankalar paylaşır!"},
			{"say": "ali", "text": "Sen gerçek kankasın!"},
			{"title": "Sen olsan paylaşır mıydın? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "lav", "name": "Bölüm 15: Yer Lav!", "set": "park", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "park.bank", "look": "park.agac"},
			{"place": "zeynep", "at": "park.bank_yani", "look": "park.bank"},
			{"place": "ali", "at": "park.agac", "look": "park.bank"},
			{"cam": "park.kam_bank", "look": "park.bank", "t": 0},
			{"title": "Yer Lav!", "t": 1.3},
			{"say": "ali", "text": "Yeni oyun: Yer lav! Yere basan yanar!"},
			{"zoom": 0.6},
			{"say": "zeynep", "text": "Bankta güvendeyim!"},
			{"say": "emir", "text": "Ali, sen yerdesin ama..."},
			{"shake": 0.4},
			{"say": "ali", "text": "Aaa! Yanıyorum! Yanıyorum!"},
			{"walk": "ali", "to": "park.ortu"},
			{"cam": "park.kam_genel", "look": "park.ortu", "t": 0},
			{"say": "ali", "text": "Piknik örtüsü güvenli bölge! Kurtuldum!"},
			{"say": "zeynep", "text": "Kim söyledi onu?"},
			{"say": "ali", "text": "Ben. Oyunu ben buldum, kuralı ben koyarım!"},
			{"cam": "park.kam_bank", "look": "park.bank", "t": 0},
			{"say": "emir", "text": "O zaman yeni kural: Örtü de lav!"},
			{"say": "ali", "text": "Hayır! Bu haksızlık!"},
			{"title": "Yer lav oyununda en sevdiğin yer neresi? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "sabah", "name": "Bölüm 16: 5 Dakika Daha", "set": "ev", "time": 0.3,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.mutfak", "look": "ev.yatak_yani"},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 0},
			{"title": "5 Dakika Daha", "t": 1.3},
			{"say": "anne", "text": "Emir, kalk! Okula geç kalacaksın!"},
			{"say": "emir", "text": "5 dakika daha anne..."},
			{"wait": 0.6},
			{"say": "anne", "text": "Emir! Kalk artık!"},
			{"say": "emir", "text": "5 dakika dahaaa..."},
			{"cam": "ev.kam_mutfak", "look": "ev.mutfak", "t": 0},
			{"say": "anne", "text": "Hmm. Kahvaltıda çikolatalı krep var ama..."},
			{"zoom": 0.6},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.masa", "look": "ev.mutfak"},
			{"shake": 0.3},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 0},
			{"say": "emir", "text": "Günaydın anneciğim! Ben hazırım!"},
			{"say": "anne", "text": "Şaka yaptım. Kahvaltıda peynir var."},
			{"say": "emir", "text": "Anneee! Bu da mı 1 Nisan?!"},
			{"title": "Sen sabah kaç kere 5 dakika daha dersin? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "penalti", "name": "Bölüm 17: Penaltı Ustası", "set": "saha", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "saha.penalti", "look": "saha.kale_sol"},
			{"place": "ali", "at": "saha.kale_sol", "look": "saha.penalti"},
			{"place": "zeynep", "at": "saha.kenar", "look": "saha.penalti"},
			{"cam": "saha.kam_genel", "look": "saha.orta", "t": 0},
			{"title": "Penaltı Ustası", "t": 1.3},
			{"say": "zeynep", "text": "Son dakika! Skor berabere! Penaltı Emir'de!"},
			{"cam": "saha.kam_kale", "look": "saha.penalti", "t": 0},
			{"say": "ali", "text": "Emir, kaleci benim. Hiçbir top geçmez!"},
			{"say": "emir", "text": "Ali, arkana bak! Uçan inek!"},
			{"turn": "ali", "to": "saha.kenar"},
			{"say": "ali", "text": "Nerede? Nerede?!"},
			{"zoom": 0.6},
			{"walk": "emir", "to": "saha.kale_sol"},
			{"shake": 0.4},
			{"say": "zeynep", "text": "GOOOL! Emir kazandı!"},
			{"turn": "ali", "to": "saha.kale_sol"},
			{"say": "ali", "text": "Hile bu! Uçan inek yoktu!"},
			{"cam": "saha.kam_kenar", "look": "saha.kenar", "t": 0},
			{"say": "zeynep", "text": "Ali... Arkana bak."},
			{"say": "ali", "text": "Beni ikinci kez kandıramazsın!"},
			{"say": "emir", "text": "Ciddiyim Ali! Bu sefer gerçekten uçan inek var!"},
			{"title": "Sence gol sayılır mı? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "hayal", "name": "Bölüm 18: Annemin Hayali İçin", "set": "bakkal", "time": 0.55,
		"steps": [
			{"place": "emir", "at": "bakkal.dis", "look": "bakkal.kapi"},
			{"place": "ali", "at": "bakkal.kapi", "look": "bakkal.dis"},
			{"place": "bakkal", "at": "bakkal.tezgah_arka", "look": "bakkal.tezgah_on"},
			{"cam": "bakkal.kam_dis", "look": "bakkal.dis", "t": 0},
			{"say": "emir", "text": "Ali! Kumbaramı kırdım! Tam 3 lira!"},
			{"title": "Annemin Hayali İçin", "t": 1.2},
			{"say": "ali", "text": "3 lira mı? Onunla sakız bile alamazsın."},
			{"say": "emir", "text": "Yarın annemin doğum günü. Hep çiçekli bir kupa istiyor."},
			{"walk": "emir", "to": "bakkal.tezgah_on"},
			{"walk": "ali", "to": "bakkal.raf"},
			{"cam": "bakkal.kam_ic", "look": "bakkal.tezgah_on", "t": 0},
			{"say": "emir", "text": "Amca, çiçekli kupa kaç lira?"},
			{"say": "bakkal", "text": "50 lira evladım."},
			{"zoom": 0.6},
			{"say": "emir", "text": "50 mi... Ama benim sadece 3 liram var."},
			{"cam": "bakkal.kam_tezgah", "look": "bakkal.raf", "t": 0},
			{"say": "ali", "text": "Hıh. Ben demiştim. Hadi gidelim."},
			{"turn": "ali", "to": "bakkal.tezgah_on"},
			{"wait": 0.8},
			{"say": "ali", "text": "...Dur. Benim de harçlığım var. Al, 47 lira."},
			{"shake": 0.3},
			{"cam": "bakkal.kam_ic", "look": "bakkal.tezgah_on", "t": 0},
			{"say": "emir", "text": "Ali! Ama bu senin bisiklet paran!"},
			{"say": "ali", "text": "Bisiklet bekler. Annenin hayali beklemez."},
			{"say": "bakkal", "text": "Siz ne iyi çocuklarsınız. Kupa benden hediye!"},
			{"say": "emir", "text": "Ali, sen dünyanın en iyi arkadaşısın!"},
			{"say": "ali", "text": "Kimseye söyleme. Havam bozulur."},
			{"title": "Senin en iyi arkadaşın kim? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "tuzak", "name": "Bölüm 19: Ali'nin Tuzağı", "set": "okul", "time": 0.4,
		"steps": [
			{"place": "ali", "at": "okul.sinif_kapi", "look": "okul.tahta"},
			{"place": "emir", "at": "okul.bahce", "look": "okul.sinif_kapi"},
			{"cam": "okul.kam_sinif", "look": "okul.sinif_kapi", "t": 0},
			{"say": "ali", "text": "Hehehe. Kapının üstüne su kovası koydum."},
			{"title": "Ali'nin Tuzağı", "t": 1.2},
			{"say": "ali", "text": "Emir kapıyı açınca şıpıdık! Çok gülecekler!"},
			{"cam": "okul.kam_bahce", "look": "okul.bahce", "t": 0},
			{"say": "emir", "text": "Ali içeride ne yapıyor acaba? Çok sessiz..."},
			{"walk": "emir", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_sinif", "look": "okul.sinif_kapi", "t": 0},
			{"zoom": 0.6},
			{"say": "ali", "text": "Geliyor... Geliyor... 3, 2, 1!"},
			{"say": "emir", "text": "Aa, kapı açık. Öğretmenim, önden buyurun!"},
			{"place": "ogretmen", "at": "okul.bahce", "look": "okul.sinif_kapi"},
			{"walk": "ogretmen", "to": "okul.sinif_kapi"},
			{"shake": 0.6},
			{"say": "ogretmen", "text": "ALİİİ! Ben sırılsıklam oldum!"},
			{"say": "ali", "text": "Öğretmenim, yemin ederim o kova sizin için değildi!"},
			{"say": "emir", "text": "Kimin içindi peki, Ali?"},
			{"say": "ali", "text": "Iıı... Kovanın kendisi için. Susamıştı."},
			{"title": "Tuzak kuran tuzağa düşer! Sence Ali ceza alır mı?", "t": 2.5},
		],
	},
	{
		"id": "pazarlik", "name": "Bölüm 20: Pazarlık Ustası", "set": "pazar", "time": 0.35,
		"steps": [
			{"place": "bakkal", "at": "pazar.tezgah1_arka", "look": "pazar.tezgah1_on"},
			{"place": "emir", "at": "pazar.giris", "look": "pazar.orta"},
			{"place": "ali", "at": "pazar.orta", "look": "pazar.giris"},
			{"cam": "pazar.kam_genel", "look": "pazar.orta", "t": 0},
			{"say": "ali", "text": "Emir! Pazarda en iyi pazarlığı kim yapar? Tabii ki ben!"},
			{"title": "Pazarlık Ustası", "t": 1.2},
			{"walk": "ali", "to": "pazar.tezgah1_on"},
			{"walk": "emir", "to": "pazar.tezgah2_on"},
			{"cam": "pazar.kam_tezgah", "look": "pazar.tezgah1_on", "t": 0},
			{"say": "ali", "text": "Amca, bu çilekler kaç lira?"},
			{"say": "bakkal", "text": "Kilosu 40 lira evladım."},
			{"say": "ali", "text": "40 mı?! 50 veririm!"},
			{"zoom": 0.6},
			{"say": "bakkal", "text": "Eee... Tamam, sen bilirsin."},
			{"turn": "ali", "to": "pazar.tezgah2_on"},
			{"say": "ali", "text": "Gördün mü Emir? Pazarlığı kazandım!"},
			{"shake": 0.3},
			{"say": "emir", "text": "Ali... Pazarlıkta fiyat düşürülür, yükseltilmez!"},
			{"say": "ali", "text": "Aaa! Amca, 30 versem?"},
			{"say": "bakkal", "text": "Anlaşma anlaşmadır. Ama al, bir kilo da hediye!"},
			{"title": "Sen hiç pazarlık yaptın mı? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "salincak", "name": "Bölüm 21: Salıncak Sırası", "set": "oyun", "time": 0.4,
		"steps": [
			{"place": "ali", "at": "oyun.salincak", "look": "oyun.orta"},
			{"place": "emir", "at": "oyun.giris", "look": "oyun.orta"},
			{"place": "komsu_cocuk", "at": "oyun.kum", "look": "oyun.orta"},
			{"cam": "oyun.kam_genel", "look": "oyun.orta", "t": 0},
			{"say": "emir", "text": "Ali! Biraz da ben sallanabilir miyim?"},
			{"title": "Salıncak Sırası", "t": 1.2},
			{"walk": "emir", "to": "oyun.orta"},
			{"cam": "oyun.kam_salincak", "look": "oyun.salincak", "t": 0},
			{"say": "ali", "text": "Olmaz! Bu salıncak benim. 5 dakika daha!"},
			{"say": "emir", "text": "Ama sen sabahtan beri sallanıyorsun..."},
			{"say": "ali", "text": "5 dakika daha dedim!"},
			{"zoom": 0.6},
			{"walk": "emir", "to": "oyun.kaydirak_yani"},
			{"cam": "oyun.kam_kaydirak", "look": "oyun.kaydirak_yani", "t": 0},
			{"say": "emir", "text": "Peki. Ben de kaydıraktan kayarım, sonra kumdan kale yaparım!"},
			{"walk": "emir", "to": "oyun.kum"},
			{"say": "komsu_cocuk", "text": "Abi, kaleye bir kule de yapalım mı?"},
			{"say": "emir", "text": "Tabii! Hem de en büyüğünü!"},
			{"cam": "oyun.kam_genel", "look": "oyun.kum", "t": 0},
			{"turn": "ali", "to": "oyun.kum"},
			{"say": "ali", "text": "Hey! Ben de kale yapmak istiyorum!"},
			{"shake": 0.3},
			{"walk": "ali", "to": "oyun.orta"},
			{"say": "emir", "text": "Gel Ali! Salıncak da kale de paylaşınca daha eğlenceli."},
			{"say": "ali", "text": "Tamam... Ama kulenin tepesi benim!"},
			{"title": "Sen salıncakta sıra bekler misin? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "kalem", "name": "Bölüm 22: Ali'nin Sihirli Kalemi", "set": "okul", "time": 0.3,
		"steps": [
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sira_1"},
			{"place": "emir", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "ali", "at": "okul.sira_2", "look": "okul.sira_1"},
			{"cam": "okul.kam_sinif", "look": "okul.sira_2", "t": 0},
			{"say": "ali", "text": "Emir, bak! Bu sihirli kalem. Soruları kendi kendine çözüyor!"},
			{"title": "Ali'nin Sihirli Kalemi", "t": 1.2},
			{"say": "emir", "text": "Kalem kendi kendine mi yazıyor? Hiç sanmam Ali."},
			{"say": "ogretmen", "text": "Çocuklar, sürpriz! Şimdi kısa bir sınav yapıyoruz."},
			{"zoom": 0.6},
			{"say": "ali", "text": "Hiç sorun değil! Sihirli kalemim hazır!"},
			{"cam": "okul.kam_tahta", "look": "okul.sira_2", "t": 0},
			{"say": "ali", "text": "Hadi kalem, yaz! Yaz dedim! Neden yazmıyorsun?!"},
			{"shake": 0.3},
			{"turn": "ogretmen", "to": "okul.sira_2"},
			{"say": "ogretmen", "text": "Ali, kalemler sadece çalışan çocuklar için sihirlidir."},
			{"say": "emir", "text": "Ben dün akşam çalıştım. Benim kalemim de sihirli oldu!"},
			{"say": "ali", "text": "Tamam tamam... Bu akşam ben de kalemime ders çalıştıracağım!"},
			{"title": "Sence sihirli kalem var mı? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "kaydirak", "name": "Bölüm 23: Ali Kaydıraktan Korkar mı?", "set": "oyun", "time": 0.45,
		"steps": [
			{"place": "ali", "at": "oyun.kaydirak_yani", "look": "oyun.kaydirak_alt"},
			{"place": "emir", "at": "oyun.orta", "look": "oyun.kaydirak_yani"},
			{"place": "komsu_cocuk", "at": "oyun.kaydirak_alt", "look": "oyun.orta"},
			{"cam": "oyun.kam_genel", "look": "oyun.kaydirak_yani", "t": 0},
			{"say": "ali", "text": "Ben mi korkmak? Bu kaydırak bana çok küçük!"},
			{"title": "Ali Kaydıraktan Korkar mı?", "t": 1.2},
			{"say": "emir", "text": "O zaman hadi kay, Ali!"},
			{"cam": "oyun.kam_kaydirak", "look": "oyun.kaydirak_yani", "t": 0},
			{"say": "ali", "text": "Şey... Önce ısınmam lazım. Profesyoneller hep ısınır."},
			{"say": "komsu_cocuk", "text": "Ben üç yaşındayım ve on kere kaydım!"},
			{"zoom": 0.6},
			{"say": "ali", "text": "Iıı... Bugün kaydırak çok kaygan görünüyor."},
			{"walk": "emir", "to": "oyun.kaydirak_alt"},
			{"say": "emir", "text": "Ali, korkmak ayıp değil. Beraber kayalım mı?"},
			{"shake": 0.3},
			{"say": "ali", "text": "Beraber mi? Tamam! Ama ben önde, sen arkada tut beni!"},
			{"cam": "oyun.kam_genel", "look": "oyun.kaydirak_alt", "t": 0},
			{"say": "ali", "text": "Vay! Bir daha! Bir daha kayalım!"},
			{"title": "Sen en çok hangi oyuncağı seversin? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "asi_korkusu", "name": "Bölüm 24: Ali Hasta Numarası Yapıyor", "set": "hastane", "time": 0.35,
		"steps": [
			{"place": "ali", "at": "hastane.yatak_1", "look": "hastane.yatak_1_yani", "lie": true},
			{"place": "emir", "at": "hastane.giris", "look": "hastane.danisma"},
			{"place": "doktor", "at": "hastane.danisma_arka", "look": "hastane.danisma"},
			{"cam": "hastane.kam_yatak", "look": "hastane.yatak_1", "t": 0},
			{"say": "ali", "text": "Ahh... Çok hastayım. Bugün matematik sınavına giremem..."},
			{"title": "Ali Hasta Numarası Yapıyor", "t": 1.2},
			{"walk": "emir", "to": "hastane.yatak_1_yani"},
			{"say": "emir", "text": "Ali! Sana çorba getirdim. Ama sınav ertelendi, yarın olacakmış."},
			{"say": "ali", "text": "Ertelendi mi? Yaşasın! Hemen iyileştim!"},
			{"place": "ali", "at": "hastane.yatak_1_yani", "look": "hastane.danisma"},
			{"shake": 0.3},
			{"walk": "doktor", "to": "hastane.danisma"},
			{"cam": "hastane.kam_ic", "look": "hastane.danisma", "t": 0},
			{"say": "doktor", "text": "Bu kadar hızlı iyileşen hasta görmedim. Ama emin olmak için bir iğne yapalım."},
			{"zoom": 0.6},
			{"say": "ali", "text": "İğne mi?! Ahh, yine hastalandım!"},
			{"say": "emir", "text": "Ali, en iyi ilaç doğruyu söylemek!"},
			{"title": "Sen hiç hasta numarası yaptın mı? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "cuzdan", "name": "Bölüm 25: Kayıp Cüzdan", "set": "pazar", "time": 0.4,
		"steps": [
			{"place": "bakkal", "at": "pazar.tezgah1_arka", "look": "pazar.tezgah1_on"},
			{"place": "emir", "at": "pazar.cesme_yani", "look": "pazar.orta"},
			{"place": "ali", "at": "pazar.orta", "look": "pazar.cesme_yani"},
			{"cam": "pazar.kam_genel", "look": "pazar.orta", "t": 0},
			{"say": "emir", "text": "Ali, bak! Çeşmenin yanında bir cüzdan buldum!"},
			{"title": "Kayıp Cüzdan", "t": 1.2},
			{"say": "ali", "text": "İçinde para var mı? Hepsiyle dondurma alalım!"},
			{"zoom": 0.6},
			{"say": "emir", "text": "Olmaz Ali! Bu birinin emeği. Sahibini bulmalıyız."},
			{"walk": "emir", "to": "pazar.tezgah1_on"},
			{"walk": "ali", "to": "pazar.tezgah2_on"},
			{"cam": "pazar.kam_tezgah", "look": "pazar.tezgah1_on", "t": 0},
			{"say": "emir", "text": "Amca, bu cüzdan sizin mi?"},
			{"say": "bakkal", "text": "Aaa! Benim cüzdanım! Bütün sabah aradım. Çok teşekkür ederim evladım!"},
			{"say": "bakkal", "text": "Dürüstlüğün için al, iki dondurma benden!"},
			{"shake": 0.3},
			{"turn": "ali", "to": "pazar.tezgah1_on"},
			{"say": "ali", "text": "Vay... Dürüst olunca dondurma bedavaya geliyormuş!"},
			{"say": "emir", "text": "Dondurma için değil Ali, doğrusu bu olduğu için!"},
			{"title": "Sen cüzdan bulsan ne yapardın? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "kaleci", "name": "Bölüm 26: Dünyanın En İyi Kalecisi", "set": "saha", "time": 0.4,
		"steps": [
			{"place": "ali", "at": "saha.kale_sol", "look": "saha.penalti"},
			{"place": "emir", "at": "saha.penalti", "look": "saha.kale_sol"},
			{"place": "komsu_cocuk", "at": "saha.kenar", "look": "saha.orta"},
			{"cam": "saha.kam_genel", "look": "saha.kale_sol", "t": 0},
			{"say": "ali", "text": "Ben dünyanın en iyi kalecisiyim! Hiçbir top geçemez!"},
			{"title": "Dünyanın En İyi Kalecisi", "t": 1.2},
			{"cam": "saha.kam_kale", "look": "saha.penalti", "t": 0},
			{"say": "emir", "text": "Hazır mısın Ali? Vuruyorum!"},
			{"say": "ali", "text": "Vur bakalım! Gözlerim kartal gibi!"},
			{"shake": 0.4},
			{"say": "komsu_cocuk", "text": "Goool!"},
			{"zoom": 0.6},
			{"say": "ali", "text": "O sayılmaz! Güneş gözüme geldi!"},
			{"say": "emir", "text": "Ali, hava bulutlu..."},
			{"say": "ali", "text": "Iıı... Bulutun arkasındaki güneş geldi!"},
			{"cam": "saha.kam_genel", "look": "saha.penalti", "t": 0},
			{"say": "emir", "text": "Peki, bu sefer sen vur, ben kaleye geçeyim!"},
			{"walk": "ali", "to": "saha.orta"},
			{"say": "ali", "text": "Tamam! Ama ben kaçırırsam rüzgâr yüzünden olur!"},
			{"title": "Sence Ali iyi bir kaleci mi? Yorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "bulasik", "name": "Bölüm 27: Bulaşık Kimde?", "set": "ev", "time": 0.6,
		"steps": [
			{"place": "anne", "at": "ev.mutfak", "look": "ev.masa"},
			{"place": "emir", "at": "ev.masa", "look": "ev.mutfak"},
			{"place": "ali", "at": "ev.kapi_ici", "look": "ev.masa"},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 0},
			{"say": "anne", "text": "Çocuklar, yemek bitti. Bulaşıkları kim yıkayacak?"},
			{"title": "Bulaşık Kimde?", "t": 1.2},
			{"say": "ali", "text": "Ben misafirim teyzeciğim! Misafir bulaşık yıkamaz!"},
			{"say": "emir", "text": "Ama Ali, sen her gün bizdesin..."},
			{"zoom": 0.6},
			{"say": "ali", "text": "Iıı... Bugün özel misafirim! Doğum günüm gibi bir şey!"},
			{"walk": "emir", "to": "ev.ocak"},
			{"cam": "ev.kam_mutfak", "look": "ev.ocak", "t": 0},
			{"say": "emir", "text": "Ben yıkarım anne. Hem sonra tatlı var, değil mi?"},
			{"say": "anne", "text": "Evet, çikolatalı pasta! Ama sadece yardım edenlere."},
			{"shake": 0.3},
			{"walk": "ali", "to": "ev.mutfak"},
			{"say": "ali", "text": "Teyzeciğim, ben aslında bulaşık şampiyonuyum! Kurulamayı bana bırakın!"},
			{"title": "Sen evde yardım eder misin? Yorumlara yaz!", "t": 2.5},
		],
	},
]


## Bir formattaki bölümler: "short" (dikey 30-60 sn) ya da "long" (yatay 5-10 dk).
static func of_format(format: String) -> Array:
	return LIST.filter(func(e: Dictionary) -> bool: return e.get("format", "short") == format)


static func find(id: String) -> Dictionary:
	for e in LIST:
		if e["id"] == id:
			return e
	return LIST[0]
