class_name Episodes
extends RefCounted
## Video senaryoları. Her bölüm bir set ve adımlardan oluşur; adımlar sırayla oynatılır (film_studio.gd).
## "format": "short" (dikey Shorts, 30-60 sn, varsayılan) ya da "long" (yatay uzun bölüm, 5-10 dk).
## Konumlar set noktasıdır ("ev.yatak", bkz. film_sets.gd POINTS) ya da Vector3.
##
## Adımlar:
##   {"title": "yazı", "t": sn}                       ekranın ortasında büyük başlık
##   {"place": "emir", "at": nokta, "look": nokta, "lie": bool}   oyuncuyu sahneye koyar
##   {"cam": nokta, "look": nokta, "t": sn}             kamerayı götürür (t=0 kesme)
##   {"say": "emir", "text": "..."}                     diyalog kutusu; okunma süresi kadar bekler
##   {"walk": "emir", "to": nokta, "wait": false}       yürür (wait false: yürürken sonraki adıma geçer)
##   {"lie": "emir", "value": false}                    yatar/kalkar
##   {"turn": "emir", "to": nokta}                      bir yere döner
##   {"hide": "emir"}                                   sahneden çıkarır
##   {"time": 0.26}                                     günün saati (0.25 gündoğumu, 0.5 öğle)
##   {"wait": sn}
##   {"zoom": sn}                                      komik anda hızlı yakınlaşma
##   {"shake": sn}                                     kamera sarsıntısı
## Yazım kuralları: docs/senaryo-rehberi.md

const LIST := [
	{
		"id": "bolum1", "name": "Bölüm 1: Okul Sabahı", "set": "ev", "time": 0.27,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.ocak", "look": "ev.mutfak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nBölüm 1: Okul Sabahı", "t": 2.5},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 2.0},
			{"say": "emir", "text": "Hıı... Sabah mı oldu?"},
			{"cam": "ev.kam_mutfak", "look": "ev.ocak", "t": 0},
			{"say": "anne", "text": "Emir! Kalk oğlum, okula geç kalacaksın!"},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 0},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"say": "emir", "text": "Tamam anne, geliyorum!"},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 1.2},
			{"walk": "emir", "to": "ev.mutfak"},
			{"turn": "anne", "to": "ev.mutfak"},
			{"turn": "emir", "to": "ev.ocak"},
			{"say": "anne", "text": "Günaydın uykucu! Önce elini yüzünü yıka, sonra kahvaltı."},
			{"say": "emir", "text": "Günaydın anne! Kahvaltıda ne var?"},
			{"say": "anne", "text": "Senin sevdiğin fırın elma ve çilek!"},
			{"say": "emir", "text": "Yaşasın! En sevdiğim!"},
			{"walk": "emir", "to": "ev.canta"},
			{"say": "emir", "text": "Çantam, kalemlerim, defterim... Hepsi tamam!"},
			{"walk": "anne", "to": "ev.masa", "wait": false},
			{"walk": "emir", "to": "ev.kapi_ici"},
			{"turn": "emir", "to": "ev.masa"},
			{"say": "anne", "text": "Beslenmeni unutma. Arkadaşlarına iyi davran!"},
			{"say": "emir", "text": "Merak etme anne. Görüşürüz!"},
			{"cam": "ev.kam_kapi", "look": "ev.kapi_disi", "t": 0},
			{"walk": "emir", "to": "ev.yol"},
			{"title": "Yarın: Okulda ilk gün!", "t": 2.5},
		],
	},
	{
		"id": "okul1", "name": "Bölüm 2: Teneffüs", "set": "okul", "time": 0.4,
		"steps": [
			{"place": "emir", "at": "okul.kaydirak", "look": "okul.bahce"},
			{"place": "ali", "at": "okul.bahce", "look": "okul.kaydirak"},
			{"place": "zeynep", "at": "okul.top_alani", "look": "okul.bahce"},
			{"cam": "okul.kam_bahce", "look": "okul.bahce", "t": 0},
			{"title": "EmirCRAFT\nBölüm 2: Teneffüs", "t": 2.5},
			{"say": "ali", "text": "Emir! Saklambaç oynayalım mı?"},
			{"walk": "emir", "to": Vector3(55.5, 11, 17.5)},
			{"turn": "emir", "to": "okul.bahce"},
			{"say": "emir", "text": "Olur! Ama bu sefer ebe sensin Ali!"},
			{"walk": "zeynep", "to": Vector3(53.5, 11, 17.0)},
			{"say": "zeynep", "text": "Ben de varım! Kum havuzunun arkasına saklanacağım."},
			{"say": "ali", "text": "Tamam, gözlerimi kapatıyorum. Bir... iki... üç..."},
			{"walk": "emir", "to": "okul.sinif_kapi", "wait": false},
			{"walk": "zeynep", "to": "okul.top_alani"},
			{"say": "ali", "text": "...on! Önüm arkam sağım solum sobe!"},
			{"cam": "okul.kam_sinif", "look": "okul.sinif_kapi", "t": 1.5},
			{"say": "emir", "text": "Hiii... Sınıfa saklandım, burayı asla bulamaz!"},
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"say": "ogretmen", "text": "Emir? Teneffüste sınıfta ne arıyorsun?"},
			{"turn": "emir", "to": "okul.tahta"},
			{"say": "emir", "text": "Şşş öğretmenim! Saklambaç oynuyoruz!"},
			{"say": "ogretmen", "text": "Hahaha! O zaman ben seni görmedim."},
			{"title": "Ali Emir'i bulabilecek mi?\nDevamı gelecek bölümde!", "t": 3.0},
		],
	},
	{
		"id": "hasta", "name": "Bölüm 3: Sahte Hasta", "set": "ev", "time": 0.28,
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.kapi_ici", "look": "ev.yatak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nBölüm 3: Sahte Hasta", "t": 2.5},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 1.5},
			{"say": "emir", "text": "(Bugün matematik sınavı var... Bir planım var!)"},
			{"say": "emir", "text": "Anneee... Öhö öhö! Çok hastayım, okula gidemem..."},
			{"walk": "anne", "to": "ev.yatak_yani"},
			{"turn": "anne", "to": "ev.yatak"},
			{"say": "anne", "text": "Hmm... Ateşin var mı bakalım?"},
			{"say": "emir", "text": "Evet! Çok yüksek! Belki bin derece!"},
			{"say": "anne", "text": "Bin derece mi? O zaman bugünkü lunaparka gidemeyiz..."},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"turn": "anne", "to": "ev.yatak_yani"},
			{"say": "emir", "text": "LUNAPARK MI?! İyileştim! Mucize oldu!"},
			{"say": "anne", "text": "Hahaha! Lunapark hafta sonu. Şimdi hadi okula, sınavın var!"},
			{"say": "emir", "text": "Eyvah... Yakalandım!"},
			{"title": "Yalan söyleyen yakalanır!", "t": 2.5},
		],
	},
	{
		"id": "odev", "name": "Bölüm 4: Ödevi Köpek Yedi", "set": "okul", "time": 0.35,
		"steps": [
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"place": "ali", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "zeynep", "at": "okul.sira_2", "look": "okul.tahta"},
			{"place": "emir", "at": "okul.sira_3", "look": "okul.tahta"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"title": "EmirCRAFT\nBölüm 4: Ödevi Köpek Yedi", "t": 2.5},
			{"say": "ogretmen", "text": "Günaydın çocuklar! Ödevlerinizi toplayalım."},
			{"say": "zeynep", "text": "Buyurun öğretmenim, iki sayfa yazdım!"},
			{"say": "ogretmen", "text": "Aferin Zeynep! Ali, senin ödevin?"},
			{"say": "ali", "text": "Öğretmenim... Ödevimi köpeğim yedi!"},
			{"say": "ogretmen", "text": "Ali, senin köpeğin yok ki."},
			{"say": "ali", "text": "Eee... Komşunun köpeği! Çok acıkmıştı!"},
			{"cam": "okul.kam_tahta", "look": "okul.sira_3", "t": 1.0},
			{"say": "ogretmen", "text": "Peki Emir, senin ödevin nerede?"},
			{"say": "emir", "text": "Benimki burada öğretmenim! Ama biraz... ıslak."},
			{"say": "ogretmen", "text": "Islak mı? Ne oldu ona?"},
			{"say": "emir", "text": "Ali'nin komşusunun köpeği onu da yalamış!"},
			{"say": "zeynep", "text": "Hahaha! O köpek bütün sınıfın ödevini yiyecek!"},
			{"say": "ogretmen", "text": "Tamam, tamam! Yarın ödevler kuru ve eksiksiz gelsin!"},
			{"title": "Ödevini zamanında yap,\nköpeğe fırsat verme!", "t": 3.0},
		],
	},
	{
		"id": "noobpro", "name": "Bölüm 5: Acemi vs Usta", "set": "ev", "time": 0.3,
		"steps": [
			{"place": "ali", "at": "ev.masa", "look": "ev.ocak"},
			{"place": "zeynep", "at": "ev.mutfak", "look": "ev.ocak"},
			{"cam": "ev.kam_mutfak", "look": "ev.masa", "t": 0},
			{"title": "Acemi vs Usta: Kahvaltı", "t": 1.3},
			{"say": "ali", "text": "Acemi kahvaltı hazırlıyor..."},
			{"say": "ali", "text": "Elmayı ocağa koydum, on saat bekleyeceğim!"},
			{"zoom": 0.4},
			{"cam": "ev.kam_oda", "look": "ev.mutfak", "t": 0},
			{"say": "zeynep", "text": "Usta kahvaltı hazırlıyor!"},
			{"say": "zeynep", "text": "Fırın elma, çilek, hepsi on saniyede hazır!"},
			{"place": "emir", "at": "ev.kapi_ici", "look": "ev.mutfak"},
			{"cam": "ev.kam_yatak", "look": "ev.kapi_ici", "t": 0},
			{"say": "emir", "text": "Peki ya dâhi kahvaltı?"},
			{"walk": "emir", "to": "ev.masa"},
			{"say": "emir", "text": "Anneeee! Kahvaltı hazır mı?"},
			{"place": "anne", "at": "ev.ocak", "look": "ev.masa"},
			{"shake": 0.4},
			{"say": "anne", "text": "Hazır oğlum, gel otur!"},
			{"zoom": 0.5},
			{"say": "emir", "text": "İşte dâhi yöntemi: Annem!"},
			{"title": "Sen hangisisin?\nYorumlara yaz!", "t": 2.5},
		],
	},
	{
		"id": "uzun1", "name": "Uzun 1: Büyük Okul Günü", "set": "ev", "time": 0.27, "format": "long",
		"steps": [
			{"place": "emir", "at": "ev.yatak", "lie": true},
			{"place": "anne", "at": "ev.ocak", "look": "ev.mutfak"},
			{"cam": "ev.kam_dis", "look": "ev.kapi_disi", "t": 0},
			{"title": "EmirCRAFT\nEmir'in Büyük Okul Günü", "t": 3.0},
			{"cam": "ev.kam_yatak", "look": "ev.yatak", "t": 2.5},
			{"say": "emir", "text": "Hıı... Rüyamda dev bir çilek beni kovalıyordu..."},
			{"say": "emir", "text": "Neyse ki uyandım. Bugün günlerden ne?"},
			{"say": "emir", "text": "Dur bir dakika... Bugün okulda BİLİM FUARI var!"},
			{"zoom": 0.5},
			{"lie": "emir", "value": false},
			{"place": "emir", "at": "ev.yatak_yani", "look": "ev.mutfak"},
			{"say": "emir", "text": "Anneee! Bilim fuarı bugün! Projemi unuttum!"},
			{"cam": "ev.kam_mutfak", "look": "ev.ocak", "t": 0},
			{"say": "anne", "text": "Sakin ol Emir. Önce derin bir nefes al."},
			{"say": "anne", "text": "Proje ne hakkında olacaktı?"},
			{"cam": "ev.kam_oda", "look": "ev.masa", "t": 1.2},
			{"walk": "emir", "to": "ev.mutfak"},
			{"turn": "emir", "to": "ev.ocak"},
			{"turn": "anne", "to": "ev.mutfak"},
			{"say": "emir", "text": "Bitkiler güneşten nasıl yemek yapar, onu anlatacaktım."},
			{"say": "emir", "text": "Ama saksım da yok, bitkim de yok!"},
			{"say": "anne", "text": "Bahçede çilek çalıları var ya?"},
			{"say": "emir", "text": "Evet ama çalıyı okula nasıl götüreceğim?"},
			{"say": "anne", "text": "Küçük bir dalını saksıya dikeriz. Hadi, beraber yapalım!"},
			{"say": "emir", "text": "Sen dünyanın en iyi annesisin!"},
			{"say": "anne", "text": "Biliyorum. Ama önce kahvaltı!"},
			{"walk": "anne", "to": "ev.masa", "wait": false},
			{"walk": "emir", "to": "ev.masa"},
			{"cam": "ev.kam_yatak", "look": "ev.masa", "t": 0},
			{"say": "emir", "text": "Fırın elma! Mmm, kokusu harika."},
			{"say": "anne", "text": "Yemek yerken acele etme, boğazına kaçar."},
			{"say": "emir", "text": "Acele etmiyorum... Sadece çok hızlı çiğniyorum!"},
			{"say": "anne", "text": "Hahaha. Peki fuarda kime göstereceksin projeni?"},
			{"say": "emir", "text": "Öğretmenime, Ali'ye, Zeynep'e... Bütün okula!"},
			{"say": "emir", "text": "Ali roket yapıyormuş. Zeynep de yanardağ!"},
			{"say": "anne", "text": "Yanardağ mı? Umarım sınıfı köpüğe boğmaz."},
			{"say": "emir", "text": "Boğarsa çok eğlenceli olur!"},
			{"zoom": 0.4},
			{"cam": "ev.kam_kapi", "look": "ev.bahce", "t": 0},
			{"place": "emir", "at": "ev.kapi_disi", "look": "ev.bahce"},
			{"place": "anne", "at": "ev.kapi_ici", "look": "ev.bahce"},
			{"walk": "emir", "to": "ev.bahce"},
			{"walk": "anne", "to": Vector3(7.0, 11, 10.0)},
			{"say": "anne", "text": "İşte burada. En sağlam dalı seçelim."},
			{"say": "emir", "text": "Bu mu? Bunun üstünde üç tane çilek var!"},
			{"say": "anne", "text": "Çilekleri yeme ama! Projen bunlar."},
			{"say": "emir", "text": "Bir tanecik bile mi?"},
			{"say": "anne", "text": "Bir tanecik. Diğerleri jüri için."},
			{"say": "emir", "text": "Anlaştık!"},
			{"say": "emir", "text": "Mmm... Bilimin tadı çok güzelmiş!"},
			{"shake": 0.3},
			{"cam": "ev.kam_kapi", "look": "ev.kapi_disi", "t": 0},
			{"walk": "emir", "to": "ev.kapi_disi"},
			{"turn": "emir", "to": "ev.bahce"},
			{"say": "anne", "text": "Saksın hazır. Dikkatli taşı, düşürme!"},
			{"say": "emir", "text": "Merak etme! Görüşürüz anne!"},
			{"say": "anne", "text": "İyi şanslar küçük bilim insanı!"},
			{"walk": "emir", "to": "ev.yol"},
			{"hide": "anne"},
			{"hide": "emir"},
			{"title": "Okulda...", "t": 2.0},
			{"place": "ogretmen", "at": "okul.tahta", "look": "okul.sinif_kapi"},
			{"place": "ali", "at": "okul.sira_1", "look": "okul.tahta"},
			{"place": "zeynep", "at": "okul.sira_2", "look": "okul.tahta"},
			{"place": "emir", "at": "okul.sinif_kapi", "look": "okul.tahta"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 0},
			{"say": "ogretmen", "text": "Günaydın çocuklar! Bugün büyük gün!"},
			{"say": "ogretmen", "text": "Bilim fuarına hoş geldiniz!"},
			{"say": "emir", "text": "Yetiştim! Günaydın öğretmenim!"},
			{"walk": "emir", "to": "okul.sira_3"},
			{"turn": "emir", "to": "okul.tahta"},
			{"say": "ogretmen", "text": "İlk proje Ali'den. Buyur Ali!"},
			{"walk": "ali", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "ali", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "ali", "text": "Bu benim roketim! Kartondan ve bantlardan yaptım."},
			{"say": "ali", "text": "Üç deyince fırlayacak! Bir... iki... ÜÇ!"},
			{"shake": 0.6},
			{"say": "ali", "text": "..."},
			{"say": "ali", "text": "Eee... Galiba yakıtı unuttum."},
			{"say": "zeynep", "text": "Hahaha! Roketin uyuyor Ali!"},
			{"say": "ogretmen", "text": "Çok güzel bir tasarım Ali. Yakıtı da gelecek sefere!"},
			{"walk": "ali", "to": "okul.sira_1"},
			{"cam": "okul.kam_sinif", "look": "okul.sira_2", "t": 0},
			{"say": "ogretmen", "text": "Sırada Zeynep var. Yanardağ projesi!"},
			{"walk": "zeynep", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "zeynep", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "zeynep", "text": "Yanardağımın içine karbonat koydum."},
			{"say": "zeynep", "text": "Şimdi de sirke ekliyorum. Geri çekilin!"},
			{"shake": 0.8},
			{"zoom": 0.6},
			{"say": "ali", "text": "Vaaay! Köpükler her yere taşıyor!"},
			{"say": "emir", "text": "Sınıf köpük banyosu oldu!"},
			{"say": "ogretmen", "text": "Zeynep! Bu kadar köpük olacağını söylememiştin!"},
			{"say": "zeynep", "text": "Ben de bilmiyordum öğretmenim! Bilim bu!"},
			{"say": "ogretmen", "text": "Hahaha! Tamam tamam, harika bir deney oldu."},
			{"walk": "zeynep", "to": "okul.sira_2"},
			{"cam": "okul.kam_sinif", "look": "okul.sira_3", "t": 0},
			{"say": "ogretmen", "text": "Son proje Emir'den. Hadi Emir!"},
			{"walk": "emir", "to": Vector3(55.5, 11, 3.2)},
			{"turn": "emir", "to": "okul.sinif_kapi"},
			{"cam": "okul.kam_tahta", "look": Vector3(55.5, 11, 3.2), "t": 1.0},
			{"say": "emir", "text": "Bu benim çilek bitkim. Sabah annemle diktik."},
			{"say": "emir", "text": "Bitkiler güneşten ışık alır, havadan da nefes alır."},
			{"say": "emir", "text": "Topraktan suyu çekerler ve kendi yemeklerini yaparlar!"},
			{"say": "emir", "text": "Buna fotosentez denir. Fo-to-sen-tez!"},
			{"say": "ogretmen", "text": "Harika anlattın Emir! Peki çilekler nerede?"},
			{"say": "emir", "text": "Şey... Üç tane vardı öğretmenim..."},
			{"say": "emir", "text": "Biri bilim için test edildi."},
			{"say": "ali", "text": "Test mi? Yedin yani!"},
			{"say": "emir", "text": "Bilimsel olarak tadına baktım!"},
			{"zoom": 0.5},
			{"say": "zeynep", "text": "Hahaha! En lezzetli proje seninki!"},
			{"say": "ogretmen", "text": "Hepiniz çok güzel çalıştınız çocuklar."},
			{"say": "ogretmen", "text": "Bugünün ödülü... hepinize birer çilek!"},
			{"say": "emir", "text": "Yaşasın! Bu sefer yemek serbest!"},
			{"cam": "okul.kam_sinif", "look": "okul.tahta", "t": 2.0},
			{"title": "Bilim eğlencelidir!\nBir sonraki bölümde görüşürüz!", "t": 3.5},
		],
	},
	{
		"id": "cilek", "name": "Bölüm 6: Çilek Karnı", "set": "hastane", "time": 0.45,
		"steps": [
			{"place": "emir", "at": "hastane.yatak_1", "lie": true},
			{"place": "anne", "at": "hastane.yatak_1_yani", "look": "hastane.yatak_1"},
			{"place": "doktor", "at": "hastane.danisma_arka", "look": "hastane.yatak_1"},
			{"cam": "hastane.kam_dis", "look": "hastane.giris", "t": 0},
			{"title": "Çilek Karnı", "t": 1.3},
			{"cam": "hastane.kam_yatak", "look": "hastane.yatak_1", "t": 0},
			{"say": "emir", "text": "Aaah karnım! Çok ağrıyor!"},
			{"say": "anne", "text": "Doktor bey, lütfen bakar mısınız?"},
			{"walk": "doktor", "to": Vector3(-38.6, 11, 3.6)},
			{"turn": "doktor", "to": "hastane.yatak_1"},
			{"say": "doktor", "text": "Merhaba Emir. Bugün ne yedin bakalım?"},
			{"say": "emir", "text": "Hiç! Sadece birkaç çilek..."},
			{"say": "anne", "text": "Birkaç mı? Bütün çalıyı bitirmişsin!"},
			{"zoom": 0.5},
			{"say": "doktor", "text": "Kaç tane yedin Emir?"},
			{"say": "emir", "text": "Sayamadım ki... Çok hızlı yedim!"},
			{"say": "doktor", "text": "Teşhis belli: Çilek karnı!"},
			{"say": "doktor", "text": "İlacın: bol su ve bugün hiç çilek yok."},
			{"shake": 0.4},
			{"say": "emir", "text": "HİÇ Mİ?! Bu ilaç çok acı doktor bey!"},
			{"say": "anne", "text": "Hahaha! Her şeyin fazlası zarar oğlum."},
			{"title": "Her şeyin azı karar,\nçoğu zarar!", "t": 2.5},
		],
	},
	{
		"id": "bakkal1", "name": "Bölüm 7: Çilekle Alışveriş", "set": "bakkal", "time": 0.4,
		"steps": [
			{"place": "bakkal", "at": "bakkal.tezgah_arka", "look": "bakkal.kapi"},
			{"place": "emir", "at": "bakkal.dis", "look": "bakkal.kapi"},
			{"cam": "bakkal.kam_dis", "look": "bakkal.kapi", "t": 0},
			{"title": "Çilekle Alışveriş", "t": 1.3},
			{"say": "emir", "text": "Bugün dondurma alacağım! Param da hazır!"},
			{"cam": "bakkal.kam_ic", "look": "bakkal.tezgah_on", "t": 0},
			{"walk": "emir", "to": "bakkal.tezgah_on"},
			{"turn": "emir", "to": "bakkal.tezgah_arka"},
			{"say": "bakkal", "text": "Hoş geldin Emir! Ne alıyorsun?"},
			{"say": "emir", "text": "En büyük çikolatalı dondurma lütfen!"},
			{"say": "bakkal", "text": "Buyur. Beş lira oluyor."},
			{"cam": "bakkal.kam_tezgah", "look": "bakkal.tezgah_on", "t": 0},
			{"say": "emir", "text": "Buyurun! Beş tane çilek!"},
			{"zoom": 0.6},
			{"say": "bakkal", "text": "Çilek mi? Evladım bu para değil ki!"},
			{"say": "emir", "text": "Ama oyunda çilekle her şey alınıyor!"},
			{"say": "bakkal", "text": "Hahaha! Burası gerçek bakkal, oyun değil!"},
			{"shake": 0.3},
			{"say": "emir", "text": "Peki... Çilekli dondurma yapar mısınız?"},
			{"say": "bakkal", "text": "Anlaştık! Çilekleri ver, dondurma benden!"},
			{"say": "emir", "text": "Yaşasın! Takas en iyi alışveriş!"},
			{"title": "Sen olsan ne ile takas ederdin?\nYorumlara yaz!", "t": 2.5},
		],
	},
]


## Bir formattaki bölümler: "short" (dikey 30-60 sn) ya da "long" (yatay 5-10 dk).
static func of_format(format: String) -> Array:
	return LIST.filter(func(e: Dictionary) -> bool: return e.get("format", "short") == format)


static func find(id: String) -> Dictionary:
	for e in LIST:
		if e["id"] == id:
			return e
	return LIST[0]
